export DB_DIALECT="postgresql"
export DB_USER="clj_db_util_test"
export DB_PASS="clj_db_util_test_pass"
export DB_NAME="clj_db_util_test_db"
export DB_HOST="localhost"
export DB_URL="jdbc:${DB_DIALECT}://${DB_HOST}/${DB_NAME}"
